#!/usr/bin/env bash

set -e

OS="$(uname -s)"

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/dotfiles
fi

# install tmux tpm plugin manager
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="zsh,nvim,bin,tmux,git,config,zed,herdr,agents"
  if [[ "$OS" == "Darwin" ]]; then
    STOW_FOLDERS="$STOW_FOLDERS,aerospace"
  fi
fi

pushd "$DOTFILES" || exit
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g"); do
  echo "stow $folder"
  stow -D "$folder"
  stow "$folder"
done

# VS Code's user config lives outside $HOME, at an OS-specific path
if [[ "$OS" == "Darwin" ]]; then
  VSCODE_USER_DIR="$HOME/Library/Application Support/Code/User"
else
  VSCODE_USER_DIR="$HOME/.config/Code/User"
fi
if [ -d "$VSCODE_USER_DIR" ]; then
  echo "stow vscode -> $VSCODE_USER_DIR"
  stow -t "$VSCODE_USER_DIR" -D vscode
  stow -t "$VSCODE_USER_DIR" vscode
fi
popd || exit

"$DOTFILES/nix-setup.sh"
