#!/usr/bin/env bash

# install starship
curl -fsSL https://starship.rs/install.sh | bash

# install tmux tpm plugin manager
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/dotfiles
fi

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="zsh,nvim,bin,tmux,git,config"
fi

pushd "$DOTFILES" || exit
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g"); do
  echo "stow $folder"
  stow -D "$folder"
  stow "$folder"
done
popd || exit

"$DOTFILES/nix-setup.sh"
