#!/usr/bin/env bash

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/dotfiles
fi

if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="zsh,nvim,bin,tmux,git,config"
fi

pushd "$DOTFILES" || exit
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g"); do
	echo "stow $folder"
	stow -D "$folder"
	stow "$folder"
done
popd || exit

nix-env -iA nixpkgs.myPackages
